<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-15J4PS7" failures="2" tests="2" name="Default test(failed)" time="0.159" errors="0" timestamp="2023-07-12T13:52:19 IST">
  <testcase classname="FailedTestCaseExecution.Demo" name="Test2" time="0.026">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at FailedTestCaseExecution.Demo.Test2(Demo.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test1" time="0.013">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at FailedTestCaseExecution.Demo.Test1(Demo.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedTestCaseExecution.Demo" name="Test3" time="0.0">
    <ignored/>
  </testcase> <!-- Test3 -->
</testsuite> <!-- Default test(failed) -->
